services:
    football:
        build: ./project/
        command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
        ports:
            - "8000:8000"
        networks:
            - db
        depends_on:
            db:
                condition: service_healthy
        healthcheck:
            test: ["CMD", "curl", "--fail", "http://localhost:8000/football/players"]
            interval: 3s
            timeout: 5s
        restart: unless-stopped
    db:
        image: postgres:14.7
        environment:
            POSTGRES_DB: footballdb
            POSTGRES_USER: oleg
            POSTGRES_PASSWORD: 123456
            PGDATA: /var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "echo 'SELECT 1;' | psql -U oleg -d footballdb"]
            interval: 3s
            timeout: 5s
        restart: unless-stopped
        ports:
            - "5432:5432"
        volumes:
            - ./pgdata:/var/lib/postgresql/data
        networks:
            - db
    nginx:
        image: nginx:1.21.3
        ports:
          - "8080:8080"
        volumes:
          - ./project/nginx.conf:/etc/nginx/nginx.conf
        networks:
          - db
        depends_on:
            football:
                condition: service_healthy

networks:
    db:
        driver: bridge
